# Server config
spring.application.name=language-server
server.port=${PORT:8080}
server.error.include-stacktrace=never
server.error.include-exception=false

# Swagger
springdoc.api-docs.enabled=true
springdoc.api-docs.version=OPENAPI_3_1
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/docs

# Disable Spring Security
spring.security.enabled=false

# PostgreSQL connection settings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Optional: specify the driver (Spring Boot usually detects this automatically)
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
# options: validate | update | create | create-drop
spring.jpa.hibernate.ddl-auto=update
# logs SQL statements
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
